# Generated by Django 3.2.4 on 2021-06-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_done',
            new_name='state',
        ),
        migrations.AddField(
            model_name='todo',
            name='responsible_person',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
