# Generated by Django 3.2.4 on 2021-06-06 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210606_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='responsible_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.person'),
        ),
    ]
