# Generated by Django 3.2.4 on 2021-06-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210606_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=['home', 'work', 'school', 'shopping', 'training', 'common'], max_length=10),
        ),
    ]
