# Generated by Django 3.2.4 on 2021-06-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_alter_todo_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('School', 'School'), ('Shopping', 'Shopping'), ('Training', 'Training'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High')], max_length=20, null=True),
        ),
    ]
