# Generated by Django 3.2.4 on 2021-06-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_alter_todo_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'users',
            },
        ),
    ]
